# Generated by Django 5.1.1 on 2026-04-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
