# Generated by Django 5.1.1 on 2026-05-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created"]},
        ),
    ]
