# Generated by Django 5.1.1 on 2026-05-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
