# Generated by Django 5.1.1 on 2026-05-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
    ]
