# Generated by Django 5.1.1 on 2026-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
