# Generated by Django 5.1.1 on 2026-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=150),
        ),
    ]
