# Generated by Django 5.1.1 on 2026-05-30 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mobile",
            field=models.CharField(
                default=0,
                max_length=10,
                validators=[django.core.validators.RegexValidator(message="Введите 10 цифр номера", regex="^\\d{10}$")],
            ),
            preserve_default=False,
        ),
    ]
