# Generated by Django 5.1.1 on 2026-05-30 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите 10 цифр номера", regex="^\\+38\\d{10}$"
                    )
                ],
            ),
        ),
    ]
