# Generated by Django 5.1.1 on 2026-05-31 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_order_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите 9 цифр номера", regex="^\\+380\\d{13}$"
                    )
                ],
            ),
        ),
    ]
