# Generated by Django 5.1.1 on 2026-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_order_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.CharField(max_length=13),
        ),
    ]
