# Generated by Django 5.1.1 on 2024-11-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=69)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=69)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="image")),
                ("price", models.DecimalField(decimal_places=3, max_digits=9)),
                ("categories", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.category")),
            ],
        ),
    ]
