# Generated by Django 5.1.1 on 2026-05-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_product_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"], "verbose_name": "Product"},
        ),
    ]
