# Generated by Django 5.1.1 on 2026-05-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
