# Generated by Django 5.1.1 on 2026-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
