# Generated by Django 5.1.1 on 2026-05-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
    ]
