# Generated by Django 5.1.1 on 2026-05-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
