# Generated by Django 5.1.1 on 2026-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
