# Generated by Django 5.1.1 on 2026-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reserved",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
