# Generated by Django 5.1.1 on 2026-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
