# Generated by Django 5.1.1 on 2026-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_telegramauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramauth",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
